config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'main', to: 'home#main'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  # resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'users/list', to: 'users#list'
  get 'users/:user_id', to: 'users#show', as: 'show_user'
  get 'profile', to: 'users#show', as: 'show_profile'
  get 'users/:user_id/favorites', to: 'favorites#show_favorites', as: 'favorites_user'
  get 'search', to: 'search#index', as: 'search'
  get 'categories/autocomplete', to: 'categories#autocomplete'
  get 'posts/autocomplete', to: 'posts#autocomplete'
  get 'user/autocomplete', to: 'users#autocomplete'
  get 'post/:post_id/rate/:score', to: 'rates#create', as: 'rates_create'
  get 'post/:post_id/favorite', to: 'favorites#create', as: 'favorites_create'
  get 'post/:post_id/unfavorite', to: 'favorites#delete', as: 'favorites_delete'

  resources :relationships, only: [:create, :destroy]

  resources :posts

  resources :categories, only: [:index, :show, :new, :create]

  # IF NO ROUTE MATCH REDIRECT TO 404
  get '*unmatched_route', to: 'application#render_404'
end

app/views/shared/_add_favorite.html.erb
<%= link_to favorites_create_path(post_id), remote: true do %>
  <img class="coeur_add coeur" aria-hidden="true" src="/assets/coeur2.png"/>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btnedit" %>
<% end %>

app/views/shared/_pertinence.html.erb
<% pertinence = @user.pertinence %>
<p class="star <% if pertinence >= 1 %>star-full<% else %>star-empty<% end %>"></p>
<p class="star <% if pertinence >= 2 %>star-full<% else %>star-empty<% end %>"></p>
<p class="star <% if pertinence >= 3 %>star-full<% else %>star-empty<% end %>"></p>
<p class="star <% if pertinence >= 4 %>star-full<% else %>star-empty<% end %>"></p>
<p class="star <% if pertinence == 5 %>star-full<% else %>star-empty<% end %>"></p>

app/views/shared/_profil_card.html.erb
<div class="container_profil">
    <div class="img_profil ">
      <%= link_to show_user_path(:user_id => user.id) do %>
        <img src="<%= user.avatar.present? ? user.avatar : '/assets/Avatar_default.png' %>" alt="<%= user.name + " Avatar" %>" width="100%" height="100%" />
      <% end %>
    </div>
    <div class="description_profil ">
        <p>
            <%= user.biography %>
        </p>
    </div>
    <ul>
      <% if !user.github.blank? %>
      <li class="fa" aria-hidden="true">
          <img src="/assets/github.svg">
          <a href="<%= user.github %>" title=<%= user.name + "'s Github" %>><%= user.github %></a>
      </li>
      <% end %>
      <% if !user.website.blank? %>
      <li class="fa" aria-hidden="true">
          <img src="/assets/website.svg">
          <a href="<%= user.website %>" title="<%= user.name + "'s Website" %>"><%= user.website %></a>

      </li>
      <% end %>
    </ul>
</div>

app/views/shared/_remove_favorite.html.erb
<%= link_to favorites_delete_path(post_id), remote: true do %>
  <img class="coeur_remove coeur" aria-hidden="true" src="/assets/coeur.gif"/>
  <script type="text/javascript">
  	setTimeout(function(){
  			$('.coeur_remove').attr("src","/assets/coeur.png");
  	},1500);
  </script>
<% end %>

app/views/shared/_stats.html.erb
<div class="container_view">
  <div class="box">
    <p class="title">Pertinence</p>
    <div class="content">
      <%= render partial: 'shared/pertinence', locals: {user: @user} %>
    </div>
  </div>

  <div class="box<% if action_name === 'show' %> boxfocus<% end %>">
    <%= link_to show_user_path(@user), class: "linkpage" do %>
    <p class="title">Publications</p>
    <p class="content"><%= @user.posts.count %></p>
    <% end %>
  </div>

  <div class="box<% if action_name === 'followers' %> boxfocus<% end %>">
    <%= link_to followers_user_path(@user), class: "linkpage" do %>
    <p class="title">Followers</p>
    <p id="followers" class="content"><%= @user.followers.count %></p>
    <% end %>
  </div>

  <div class="box<% if action_name === 'following' %> boxfocus<% end %>">
    <%= link_to following_user_path(@user), class: "linkpage" do %>
    <p class="title">Following</p>
    <p id ="followings" class="content"><%= @user.following.count %></p>
    <% end %>
  </div>

  <div class="box<% if action_name === 'show_favorites' %> boxfocus<% end %>">
    <%= link_to favorites_user_path(@user), class: "linkpage" do %>
    <p class="title">Favoris</p>
    <p id ="favorite_count" class="content"><%= @user.favorites.count %></p>
    <% end %>
  </div>
  <% if current_user && @user != current_user %>
  <div id="follow_form" class="box">
    <% if current_user.following?(@user) %>
    <%= render 'shared/unfollow' %>
    <% else %>
    <%= render 'shared/follow' %>
    <% end %>
  </div>
  <% elsif current_user %>
  <div class="box">
    <%= link_to 'Éditer le profil', edit_user_registration_path, :class => "btnedit" %>
  </div>
  <% end %>

</div>

app/views/shared/_stats_bar.html.erb
<div class="headerfake">
  <div id="contentfake">
    <div class="img_fake">
      <%= link_to show_user_path(:user_id => @user.id) do %>
      <img src="<%= @user.avatar.present? ? @user.avatar : '/assets/Avatar_default.png' %>" alt="<%= @user.name + " Avatar" %>" width="100%" height="auto" />
      <% end %>
    </div>

    <p class="name">
      <%= "@" + @user.name %></p>
      <div class="navfake">
        <ul>
          <li>
            <p class="title">Pertinence</p>
            <div class="content">
              <%= render partial: 'shared/pertinence', locals: {user: @user} %>
            </div>
          </li>
          <%= link_to show_user_path(@user), class: "linkpage" do %>
          <li>
            <p class="title">Publications</p>
            <p class="nb"><%= @user.posts.count %></p>
          </li>
          <% end %>
          <%= link_to followers_user_path(@user), class: "linkpage" do %>
          <li>
            <p class="title">Followers</p>
            <p class="nb"><%= @user.followers.count %></p>
          </li>
          <% end %>
          <%= link_to following_user_path(@user), class: "linkpage" do %>
          <li>
            <p class="title">Following</p>
            <p class="nb"><%= @user.following.count %></p>
          </li>
          <% end %>
          <%= link_to favorites_user_path(@user), class: "linkpage" do %>
          <li>
            <p class="title">Favoris</p>
            <p class="nb"><%= @user.favorites.count %></p>
          </li>
          <% end %>

        </ul>
        <% if @user == current_user %>
        <div class="btnfake">
          <%= link_to 'Éditer le profil', edit_user_registration_path, :class => "btnedit" %>
        </div>
        <% end %>
      </div>
    </div>

  </div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btnedit" %>
<% end %>

app/views/shared/_widget_categories.html.erb
<nav class="sidebar" role="navigation">
  <div class="container-fluid">
  <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active"><a href="<% root_path %>">All</a></li>
      <% hierarchy.each do |parent| %>
        <% if parent.subcategories.size > 0 %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span><%= parent.name %></span><p class="imgplus"><img src="/assets/plus.svg"></p></a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <% parent.subcategories.each do |category| %>
              <li class="drop_li"><a href="<%= category_path(category.id) %>"><%= category.name %></a></li>
            <% end %>
          </ul>
        </li>
        <% else %>
        <li><a href="#"><%= parent.name %></a></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
</nav>