config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'main', to: 'home#main'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  # resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'users/list', to: 'users#list'
  get 'users/:user_id', to: 'users#show', as: 'show_user'
  get 'profile', to: 'users#show', as: 'show_profile'
  get 'users/:user_id/favorites', to: 'favorites#show_favorites', as: 'favorites_user'
  get 'search', to: 'search#index', as: 'search'
  get 'categories/autocomplete', to: 'categories#autocomplete'
  get 'posts/autocomplete', to: 'posts#autocomplete'
  get 'user/autocomplete', to: 'users#autocomplete'
  get 'post/:post_id/rate/:score', to: 'rates#create', as: 'rates_create'
  get 'post/:post_id/favorite', to: 'favorites#create', as: 'favorites_create'
  get 'post/:post_id/unfavorite', to: 'favorites#delete', as: 'favorites_delete'

  resources :relationships, only: [:create, :destroy]

  resources :posts

  resources :categories, only: [:index, :show, :new, :create]

  # IF NO ROUTE MATCH REDIRECT TO 404
  get '*unmatched_route', to: 'application#render_404'
end

app/models/post.rb
class Post < ApplicationRecord

  searchkick autocomplete: [:url, :message]
  belongs_to :user
  has_many :rates
  has_many :favorites, dependent: :destroy
  has_and_belongs_to_many :categories
  validates_associated :categories
  validates :url, presence: true,
                    length: { minimum: 5 },
                    format: { with: /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }
  validates :message,
                    length: { maximum: 250 }, allow_blank: true
  validates :user_id, presence: true
  validates :category_ids, presence: true

  def average_ratings
    if self.rates.count > 0
      (self.rates.sum(:score).to_f / self.rates.count).round(1)
    else
      return 0
    end
  end
end

app/controllers/posts_controller.rb
require 'opengraph_parser'

class PostsController < ApplicationController
  before_action :authenticate_user!, except: [ :show, :autocomplete ]
  skip_before_action :verify_authenticity_token, :only => :create
  before_action :correct_user,   only: :destroy
  prepend_before_action :verify_authenticity_token, only: [:destroy]
  before_action :require_permission, only: [:destroy, :update, :edit]

  def autocomplete
    render json: Post.search(params[:query], autocomplete: false, limit: 10).map do |post|
      { title: post.url, value: 'post-' + post.id }
    end
  end

  # def index
  #   @posts = Post.where(user_id: current_user.id).paginate(:page => params[:page]).order(created_at: :desc)
  # end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @hierarchy = Category.where(public: true, parent_id: nil)
    @post = Post.new
  end

  def edit
    @hierarchy = Category.where(public: true, parent_id: nil)
    @post = Post.find(params[:id])
  end


  def create
    @post = Post.new(post_params)
    og = OpenGraph.new(@post.url)
    @post.og_title = og.title # og.title # => "Open Graph protocol"
    @post.og_type = og.type # og.type # => "website"
    @post.og_description = og.description # og.description # => ""
    @post.og_images = og.images[0] # og.images # => ["http://ogp.me/logo.png"]
    @post.user_id = current_user.id #or whatever is you session name
    if @post.save
      flash[:success] = 'La publication a bien été publiée'
      redirect_to show_profile_path
    else
      @hierarchy = Category.where(public: true, parent_id: nil)
      flash[:error] = 'Une erreur est survenue'
      redirect_to request.referrer || root_url
    end
  end

  def update
    @post = Post.find(params[:id])
    og = OpenGraph.new(@post.url)
    @post.og_title = og.title # og.title # => "Open Graph protocol"
    @post.og_type = og.type # og.type # => "website"
    @post.og_description = og.description # og.description # => ""
    @post.og_images = og.images[0] # og.images # => ["http://ogp.me/logo.png"]
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end

  private
    def post_params
      params.require(:post).permit(:url, :message, category_ids: [])
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end

    def require_permission
      if current_user.id != Post.find(params[:id]).user_id
        redirect_to main_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_card.html.erb
<article id="<%= post.id %>" class="onepost" onclick="<% link_to post_path(post)%>">
    <div class="row metadata">
        <div class="profil_img col-md-2">
          <%= link_to show_user_path(:user_id => post.user_id) do %>
            <img src="<%= post.user.avatar.present? ? post.user.avatar : '/assets/Avatar_default.png' %>" alt="<%= post.user.name + " Avatar" %>" width="100%" height="auto" />
          <% end %>
        </div>
        <div class="col-md-8 fix">
            <p class="name_post"><%= link_to show_user_path(:user_id => post.user_id) do %><%= "@" + post.user.name %><% end %></p>
            <% if current_user && post.user_id == current_user.id %>
              <div class="edit-post">
                <%= link_to '', edit_post_path(post), :class => "aedit" %>
                <%= link_to '', post_path(post),
                        method: :delete,
                        data: { confirm: 'Êtes vous sûr de vouloir supprimer cette publication ?' }, :class => "adelete"%>
              </div>
              <% end %>
            <div class="clear"></div>
            <p class="categorie_post">
              <% post.categories.each do |category| %>
                <span><%= link_to '#' + category.slug, category_path(:id => category.id) %></span>
              <% end %>
            </p>
        </div>
        <div class="col-md-2">
            <p class="time_post">
                <%= how_much_time(post.created_at) %>
            </p>
        </div>
    </div>
    <div class="row content">
        <div class="col-md-12">
            <div class="content_post">
              <p><%= post.message%></p>
            </div>
            <a href="<%= post.url %>" title="<%= post.url %>">
            <div class="iframe_post">
                <img src="<%= post.og_images %>" width="100%" height="300px" />
                <h3><%= post.og_title%></h3>
                <p><%= post.og_description%></p>
                <small><%= post.url%></small>
            </div>
            </a>
        </div>
    </div>
    <div class="row action">
        <div class="col-md-5 rank">
            <ul id="notation" class="notation">
              <% if current_user && post.user_id != current_user.id %>
              <% rate = Rate.find_by(:user_id => current_user.id, :post_id => post.id) %>
                <% score = rate ? rate.score : 0; %>
                <%= link_to rates_create_path(:post_id => post.id, :score => 1), remote: true do %>
                  <li id="star1" class="star1 star <% if score >= 1 %>star-full<% else %>star-empty<% end %>" aria-hidden="true">
                  </li>
                <% end %>
                <%= link_to rates_create_path(:post_id => post.id, :score => 2), remote: true do %>
                  <li id="star2" class="star2 star <% if score >= 2 %>star-full<% else %>star-empty<% end %>" aria-hidden="true">
                  </li>
                <% end %>
                <%= link_to rates_create_path(:post_id => post.id, :score => 3), remote: true do %>
                  <li id="star3" class="star3 star <% if score >= 3 %>star-full<% else %>star-empty<% end %>" aria-hidden="true">
                  </li>
                <% end %>
                <%= link_to rates_create_path(:post_id => post.id, :score => 4), remote: true do %>
                  <li id="star4" class="star4 star <% if score >= 4 %>star-full<% else %>star-empty<% end %>" aria-hidden="true">
                  </li>
                <% end %>
                <%= link_to rates_create_path(:post_id => post.id, :score => 5), remote: true do %>
                  <li id="star5" class="star5 star <% if score == 5 %>star-full<% else %>star-empty<% end %>" aria-hidden="true">
                  </li>
                <% end %>
              <% end %>
            </ul>
        </div>

        <div class="col-md-3 rating">
          <% if current_user && post.user_id != current_user.id %>
          <p id="ratings">
            <%= score if Rate.find_by(:user_id => current_user.id, :post_id => post.id) %>
          </p>
          <p class="ta-note">Ta note</p>
          <% end %>
        </div>
        <div class="col-md-4 favoris">
          <% if current_user && post.user_id != current_user.id %>
            <% if !Favorite.find_by(:user_id => current_user.id, :post_id => post.id) %>
              <%= render partial: 'shared/add_favorite', locals: {post_id: post.id} %>
            <% else %>
              <%= render partial: 'shared/remove_favorite', locals: {post_id: post.id} %>
            <% end %>
          <% end %>
        </div>
    </div>
    <div class="row post_stats">
      <p>Note de <span><%= post.average_ratings %></span> sur <span><%= post.rates.count %></span> votes</p>
    </div>
</article>

app/views/posts/_form.html.erb
<% if current_user %>
  <%= form_for :post, url: posts_path, html: {class: "add_post"} do |f| %>
    <h2 class="poster-une-ressource">Poster une ressource</h2>

      <%= f.label :category_id, :class => "sr-only" %><br>
      <select name="post[category_ids][]" id="post_category_id" class="selectpicker form-control" multiple data-max-options="3" data-live-search="true" title="Sujet" data-selected-text-format="count > 2" data-multiple-separator=", " data-selected-text-format="values">
        <% Category.where(public: true, parent_id: nil).each do |parent| %>
        <option value="<%= parent.id %>" data-tokens="<%= parent.id %>" class="select-bold"><%= parent.name %></option>
          <% parent.subcategories.each do |category| %>
            <option value="<%= category.id %>" data-tokens="<%= category.id %>">  <%= category.name %></option>
          <% end %>
          <option data-divider="true"></option>
        <% end %>
      </select>

      <%= f.label :url, :class => "sr-only" %><br />
      <%= f.url_field :url, :class => "form-control", placeholder: "Ressource" %>

      <%= f.label :message, :class => "sr-only" %><br />
      <%= f.text_area :message, :class => "form-control", placeholder: "Message" %>

    <p><%= f.submit "New post", :class => "btn btn-lg btn-primary btn-block" %></p>

  <p class="tu-ne-trouves-pas-de">Tu ne trouves pas de sujet correspondant à ta ressource ? <%= link_to 'Créer un nouveau sujet', new_category_path %></p>

  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div id="fixfoooter">
<%= link_to "Retour",  url_for(:back), :class => "backback" %>
<%= form_for :post, url: post_path(@post), method: :patch, html: {class: "fixnewpost add_post form-signup"} do |f| %>

  <h2>Modifier cette publication</h2>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :url, :class => "sr-only" %><br />
    <%= f.url_field :url, :class => "form-control", placeholder: "Ressource" %>

    <%= f.label :message, :class => "sr-only" %><br />
    <%= f.text_area :message, :class => "form-control", placeholder: "Message" %>

    <%= f.label :category_id, :class => "sr-only" %><br>
    <select name="post[category_ids][]" id="post_category_id" class="selectpicker form-control" multiple data-max-options="3" data-live-search="true" title="Sujet" data-selected-text-format="count > 2" data-multiple-separator=", " data-selected-text-format="values">
      <% @hierarchy.each do |parent| %>
      <!-- <%= @post.category_ids %> -->
      <option <% if @post.category_ids.include? parent.id %>selected<% end %> value="<%= parent.id %>" data-tokens="<%= parent.id %>"><b><%= parent.name %></b></option>
        <% parent.subcategories.each do |category| %>
          <option <% if @post.category_ids.include? category.id %>selected<% end %> value="<%= category.id %>" data-tokens="<%= category.id %>"><%= category.name %></option>
        <% end %>
        <option data-divider="true"></option>
      <% end %>
    </select>
  <p><%= f.submit "Modifier", :class => "btn btn-lg btn-primary btn-block" %></p>
<% end %>

</div>

app/views/posts/new.html.erb
<div id="fixfoooter">
<%= form_for :post, url: posts_path, html: {class: "fixnewpost form-signin add_post"} do |f| %>
  <h2 class="poster-une-ressource">
      Poster une ressource
  </h2>

    <%= f.label :category_id, :class => "sr-only" %><br>
    <select name="post[category_ids][]" id="post_category_id" class="selectpicker form-control" multiple data-max-options="3" data-live-search="true" title="Sujet" data-selected-text-format="count > 2" data-multiple-separator=", " data-selected-text-format="values">
      <% Category.where(public: true, parent_id: nil).each do |parent| %>
      <option value="<%= parent.id %>" data-tokens="<%= parent.id %>" class="select-bold"><%= parent.name %></option>
        <% parent.subcategories.each do |category| %>
          <option value="<%= category.id %>" data-tokens="<%= category.id %>">  <%= category.name %></option>
        <% end %>
        <option data-divider="true"></option>
      <% end %>
    </select>

    <%= f.label :url, :class => "sr-only" %><br />
    <%= f.url_field :url, :class => "form-control", placeholder: "Ressource" %>

    <%= f.label :message, :class => "sr-only" %><br />
    <%= f.text_area :message, :class => "form-control", placeholder: "Message" %>

  <p>
    <%= f.submit "New post", :class => "btn btn-lg btn-primary btn-block" %>
  </p>

<p class="tu-ne-trouves-pas-de">Tu ne trouves pas de sujet correspondant à ta ressource ? <%= link_to 'Créer un nouveau sujet', new_category_path %></p>

<% end %>
</div>

app/views/posts/show.html.erb
<div id="part" class="container gover">
    <div id="fixprofil" class="row">
        <div class="col-xs-12 col-sm-2 col-md-3">
            <%= render partial: 'shared/profil_card', locals: {user: @post.user} %>
        </div>
        <div class="col-md-7">
            <div class="name_profil">
                <%= link_to "@" + @post.user.name, user_path(@post.user.id) %>
            </div>
            <div class="row">
                <div id="postshow" class="col-md-9">
                    <%= render partial: 'posts/card', locals: {post: @post, user: @post.user} %>
                </div>
            </div>

        </div>
    </div>
</div>