config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'main', to: 'home#main'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  # resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'users/list', to: 'users#list'
  get 'users/:user_id', to: 'users#show', as: 'show_user'
  get 'profile', to: 'users#show', as: 'show_profile'
  get 'users/:user_id/favorites', to: 'favorites#show_favorites', as: 'favorites_user'
  get 'search', to: 'search#index', as: 'search'
  get 'categories/autocomplete', to: 'categories#autocomplete'
  get 'posts/autocomplete', to: 'posts#autocomplete'
  get 'user/autocomplete', to: 'users#autocomplete'
  get 'post/:post_id/rate/:score', to: 'rates#create', as: 'rates_create'
  get 'post/:post_id/favorite', to: 'favorites#create', as: 'favorites_create'
  get 'post/:post_id/unfavorite', to: 'favorites#delete', as: 'favorites_delete'

  resources :relationships, only: [:create, :destroy]

  resources :posts

  resources :categories, only: [:index, :show, :new, :create]

  # IF NO ROUTE MATCH REDIRECT TO 404
  get '*unmatched_route', to: 'application#render_404'
end

app/models/category.rb
class Category < ApplicationRecord
  searchkick autocomplete: [:name, :description]
  has_and_belongs_to_many :posts
  has_many :subcategories, :class_name => "Category", :foreign_key => "parent_id", :dependent => :destroy
  belongs_to :parent_category, :class_name => "Category"

  validates :name, length: { minimum: 2, maximum: 100 }, uniqueness: true, presence: true
  validates :description, length: { maximum: 250 }, allow_blank: true

  before_create :slugify_name
  before_update :slugify_name

  def slugify_name
    if name
       self.slug = self.name.parameterize
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def autocomplete
    data = Category.search(params[:query], autocomplete: false, limit: 10)
    render json: data.map do |category|
      { title: category.name, value: category.id }
    end
  end

  def show
    @hierarchy = Category.where(public: true, parent_id: nil)
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def get_all_oses
    @hierarchy = Category.where(public: true)
  end

  private
    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/new.html.erb
<div id="fixfoooter">
<%= form_for :category, url: categories_path, html: {class: "fixnewpost form-signup"} do |f| %>

  <h2>Proposer une catégorie</h2>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :name, :class => "sr-only" %><br />
    <%= f.text_field :name, :class => "form-control", placeholder: "Nom" %>

    <%= f.label :description, :class => "sr-only" %><br />
    <%= f.text_area :description, :class => "form-control", placeholder: "Message" %>

    <%= f.label :parent_id, :class => "sr-only" %><br>
    <%= f.collection_select :parent_id, Category.where(public: true, parent_id: nil), :id, :name, {:include_blank => "Nothing selected"}, {:class=>'form-control'} %>

  <p>
    <%= f.submit "Proposer cette catégorie", :class => "btn btn-lg btn-primary btn-block" %>
  </p>

<% end %>
</div>

app/views/categories/show.html.erb
<div class="nomcategorie">
	<img src="/assets/femme.png">
	<p><%= @category.name %></p>
</div>

<div id="part" class="mainmargin container gover">
    <div id="fixprofil" class="row">

        <div class="fixleft col-xs-12 col-sm-2 col-md-3">
					<%= render partial: 'shared/widget_categories', locals: {hierarchy: @hierarchy} %>
        </div>

        <div class="col-md-9">
            
                <div id="list_posts_main" class="fixcenter col-md-7">
					<% if @category.posts.size > 0 %>
					  <% @category.posts.each do |post| %>
					    <%= render partial: 'posts/card', locals: {post: post, user: post.user} %>
					  <% end %>
					<% else %>
						<p class="zerorelation text-center">Il n'y pas pour l'instant aucune publication dans cette catégorie</p>
					<% end %>
                </div>
                <div class="fixright col-md-5">
                  <%= render partial: 'posts/form'%>
                </div>
        
        </div>
    </div>
</div>