config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'main', to: 'home#main'
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }
  # resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'users/list', to: 'users#list'
  get 'users/:user_id', to: 'users#show', as: 'show_user'
  get 'profile', to: 'users#show', as: 'show_profile'
  get 'users/:user_id/favorites', to: 'favorites#show_favorites', as: 'favorites_user'
  get 'search', to: 'search#index', as: 'search'
  get 'categories/autocomplete', to: 'categories#autocomplete'
  get 'posts/autocomplete', to: 'posts#autocomplete'
  get 'user/autocomplete', to: 'users#autocomplete'
  get 'post/:post_id/rate/:score', to: 'rates#create', as: 'rates_create'
  get 'post/:post_id/favorite', to: 'favorites#create', as: 'favorites_create'
  get 'post/:post_id/unfavorite', to: 'favorites#delete', as: 'favorites_delete'

  resources :relationships, only: [:create, :destroy]

  resources :posts

  resources :categories, only: [:index, :show, :new, :create]

  # IF NO ROUTE MATCH REDIRECT TO 404
  get '*unmatched_route', to: 'application#render_404'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<div id="logo" lass="navbar-brand navbar-brand-centered">
			<%= link_to image_tag("/assets/logomini.svg"), root_path %>
		</div>
	</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="navbar-brand-centered">
		<% if user_signed_in? %>
		<form type="GET" action="<%= search_path %>" class="navbar-form navbar-left search-form" role="search">
			<div id="search" class="input-group">
				<input type="text" id="query" name="query" class="form-control" placeholder="Rechercher" />
				<div class="input-group-btn">
					<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
				</div>
			</div>
		</form>
		<% end %>
		<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
			<li id="user_menu" class="dropdown user_menu">
				<div class="cont_img">
					<%= link_to image_tag(current_user.avatar.present? ? current_user.avatar : '/assets/Avatar_default.png'), show_profile_path %>
				</div>

				<a id="linkname" href="#" class="namelink" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@<%= current_user.name %>
					<span class="caret"></span>
				</a>

				<ul id="dropdown-menu" class="dropdown-menu">
					<li class="linkdrop"><%= link_to 'Voir mon profil', show_profile_path %></li>
					<li class="linkdrop"><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
					<li class="divider"></li>
					<li class="signout"><%= link_to "Déconnexion", destroy_user_session_path, :method => :get %></li>
				</ul>

			</li>

			<% else %>
			<li id="login"><%= link_to "Connexion", new_user_session_path %></li>
			<% end %>
		</ul>
	</div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>Kamasutra Du Dev</title>

	<!-- Stylesheets -->
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


	<%= csrf_meta_tags %>
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	  <![endif]-->
	</head>
	<body>
			<%= render 'layouts/navbar' %>
			<header id="header">
				<div class="container-fluid">
					<% if notice %>
					<p class="alert alert-success"><%= notice %></p>
					<% end %>
					<% if alert %>
					<p class="alert alert-danger"><%= alert %></p>
					<% end %>
				</div>
			</header>
			<div class="container-fluid bg-grey">
				<%= yield %>
			</div>
			<footer>
				<div class="container-fluid">
					<p>
						© 2016 KamasutraDuDev.fr, Inc.
					</p>
				</div>
			</footer>
		</body>
		</html>